@tool
extends EditorPlugin


func _enter_tree() -> void:
	add_custom_type(
		"FastWaterSurface",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_surface.gd"),
		null
	)
	add_custom_type(
		"FastWaterInteractor",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_interactor.gd"),
		null
	)
	add_custom_type(
		"FastWaterPath",
		"MeshInstance3D",
		preload("res://addons/fast_water/scripts/fast_water_path.gd"),
		null
	)
	add_custom_type(
		"FastWaterBuoyant",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_buoyant.gd"),
		null
	)
	add_custom_type(
		"FastWaterPlanarReflection",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_planar_reflection.gd"),
		null
	)
	add_custom_type(
		"FastWaterBowWake",
		"MeshInstance3D",
		preload("res://addons/fast_water/scripts/fast_water_bow_wake.gd"),
		null
	)
	add_custom_type(
		"FastWaterVisualProfile",
		"Resource",
		preload("res://addons/fast_water/scripts/fast_water_visual_profile.gd"),
		null
	)
	add_custom_type(
		"FastWaterQuality",
		"Resource",
		preload("res://addons/fast_water/scripts/fast_water_quality.gd"),
		null
	)
	add_custom_type(
		"FastWaterBodyProfile",
		"Resource",
		preload("res://addons/fast_water/scripts/fast_water_body_profile.gd"),
		null
	)
	add_custom_type(
		"FastWaterOceanProfile",
		"Resource",
		preload("res://addons/fast_water/scripts/fast_water_ocean_profile.gd"),
		null
	)
	add_custom_type(
		"FastWaterOcean",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_ocean.gd"),
		null
	)
	add_custom_type(
		"FastWaterBodyDebugOverlay",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_body_debug_overlay.gd"),
		null
	)
	add_custom_type(
		"FastWaterAuthoringOverlay",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_authoring_overlay.gd"),
		null
	)
	add_custom_type(
		"FastWaterEnvironmentState",
		"Resource",
		preload("res://addons/fast_water/scripts/fast_water_environment_state.gd"),
		null
	)
	add_custom_type(
		"FastWaterWeatherResponse",
		"Resource",
		preload("res://addons/fast_water/scripts/fast_water_weather_response.gd"),
		null
	)
	add_custom_type(
		"FastWaterWeatherAdapter",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_weather_adapter.gd"),
		null
	)
	add_custom_type(
		"FastWaterWakeMap",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_wake_map.gd"),
		null
	)
	add_custom_type(
		"FastWaterFlowField",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_flow_field.gd"),
		null
	)
	add_custom_type(
		"FastWaterFoamField",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_foam_field.gd"),
		null
	)
	add_custom_type(
		"FastWaterFoamReactiveFx",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_foam_reactive_fx.gd"),
		null
	)
	add_custom_type(
		"FastWaterGpuWakeMap",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_gpu_wake_map.gd"),
		null
	)
	add_custom_type(
		"FastWaterBubblePool",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_bubble_pool.gd"),
		null
	)
	add_custom_type(
		"FastWaterCaustics",
		"MeshInstance3D",
		preload("res://addons/fast_water/scripts/fast_water_caustics.gd"),
		null
	)
	add_custom_type(
		"FastWaterWakeRibbon",
		"MeshInstance3D",
		preload("res://addons/fast_water/scripts/fast_water_wake_ribbon.gd"),
		null
	)
	add_custom_type(
		"FastWaterSky",
		"WorldEnvironment",
		preload("res://addons/fast_water/scripts/fast_water_sky.gd"),
		null
	)
	add_custom_type(
		"FastUnderwaterController",
		"Node",
		preload("res://addons/fast_water/scripts/fast_underwater_controller.gd"),
		null
	)
	add_custom_type(
		"FastWaterWeatherSequence",
		"Node",
		preload("res://addons/fast_water/scripts/fast_water_weather_sequence.gd"),
		null
	)
	add_custom_type(
		"FastWaterRainImpactFx",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_rain_impact_fx.gd"),
		null
	)
	add_custom_type(
		"FastWaterSplashFx",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_splash_fx.gd"),
		null
	)
	add_custom_type(
		"FastWaterWaterfall",
		"MeshInstance3D",
		preload("res://addons/fast_water/scripts/fast_water_waterfall.gd"),
		null
	)
	add_custom_type(
		"FastWaterWaterfallSprayFx",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_waterfall_spray_fx.gd"),
		null
	)
	add_custom_type(
		"FastWaterVolume",
		"Area3D",
		preload("res://addons/fast_water/scripts/fast_water_volume.gd"),
		null
	)
	add_custom_type(
		"FastWaterSwimmer",
		"Node3D",
		preload("res://addons/fast_water/scripts/fast_water_swimmer.gd"),
		null
	)
	add_autoload_singleton("FastWater", "res://addons/fast_water/scripts/fast_water_service.gd")


func _exit_tree() -> void:
	remove_autoload_singleton("FastWater")
	remove_custom_type("FastWaterSwimmer")
	remove_custom_type("FastWaterVolume")
	remove_custom_type("FastWaterWaterfallSprayFx")
	remove_custom_type("FastWaterWaterfall")
	remove_custom_type("FastWaterSplashFx")
	remove_custom_type("FastWaterRainImpactFx")
	remove_custom_type("FastWaterWeatherSequence")
	remove_custom_type("FastUnderwaterController")
	remove_custom_type("FastWaterSky")
	remove_custom_type("FastWaterWakeRibbon")
	remove_custom_type("FastWaterCaustics")
	remove_custom_type("FastWaterBubblePool")
	remove_custom_type("FastWaterGpuWakeMap")
	remove_custom_type("FastWaterFoamReactiveFx")
	remove_custom_type("FastWaterFoamField")
	remove_custom_type("FastWaterFlowField")
	remove_custom_type("FastWaterWakeMap")
	remove_custom_type("FastWaterWeatherAdapter")
	remove_custom_type("FastWaterWeatherResponse")
	remove_custom_type("FastWaterEnvironmentState")
	remove_custom_type("FastWaterAuthoringOverlay")
	remove_custom_type("FastWaterBodyDebugOverlay")
	remove_custom_type("FastWaterOcean")
	remove_custom_type("FastWaterOceanProfile")
	remove_custom_type("FastWaterBodyProfile")
	remove_custom_type("FastWaterQuality")
	remove_custom_type("FastWaterVisualProfile")
	remove_custom_type("FastWaterBowWake")
	remove_custom_type("FastWaterPlanarReflection")
	remove_custom_type("FastWaterBuoyant")
	remove_custom_type("FastWaterPath")
	remove_custom_type("FastWaterInteractor")
	remove_custom_type("FastWaterSurface")
